/*
 * runtime.c -- GeneScript runtime support library.
 *
 * The LLVM IR generated by codegen.cpp does not implement string/DNA
 * operations directly in IR; instead it emits `call` instructions to
 * these C functions (declared `extern "C"` on the LLVM side so there's
 * no C++ name mangling to deal with). This mirrors how real compilers
 * (C, Swift, Go, Rust) lean on a small C runtime for things that would
 * be painful to lower to raw IR by hand (string scanning, formatted
 * output, memory allocation).
 *
 * This file is compiled to runtime.o with clang and linked together
 * with the object code LLVM emits from the GeneScript program.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static int is_gc(char c) { return c == 'G' || c == 'C'; }

double gs_calc_gc_content(const char *seq) {
    size_t len = strlen(seq);
    if (len == 0) return 0.0;
    size_t gc = 0;
    for (size_t i = 0; i < len; i++) if (is_gc(toupper((unsigned char)seq[i]))) gc++;
    return (100.0 * (double)gc) / (double)len;
}

void gs_print_gc_value(double pct) {
    printf("GC Content: %.2f%%\n", pct);
}

long gs_calc_length(const char *seq) {
    return (long)strlen(seq);
}

void gs_print_length_value(long len, int binary) {
    if (binary) {
        char buf[64];
        int i = 63;
        buf[i--] = '\0';
        unsigned long v = (unsigned long)len;
        if (v == 0) buf[i--] = '0';
        while (v > 0 && i >= 0) {
            buf[i--] = (char)('0' + (v & 1));
            v >>= 1;
        }
        printf("Length: %s (binary)\n", &buf[i + 1]);
    } else {
        printf("Length: %ld\n", len);
    }
}

char *gs_calc_complement(const char *seq) {
    size_t len = strlen(seq);
    char *out = (char *)malloc(len + 1);
    for (size_t i = 0; i < len; i++) {
        switch (toupper((unsigned char)seq[i])) {
            case 'A': out[i] = 'T'; break;
            case 'T': out[i] = 'A'; break;
            case 'G': out[i] = 'C'; break;
            case 'C': out[i] = 'G'; break;
            default:  out[i] = seq[i]; break;
        }
    }
    out[len] = '\0';
    return out;
}

char *gs_calc_reverse(const char *seq) {
    size_t len = strlen(seq);
    char *out = (char *)malloc(len + 1);
    for (size_t i = 0; i < len; i++) out[i] = seq[len - 1 - i];
    out[len] = '\0';
    return out;
}

char *gs_calc_reverse_complement(const char *seq) {
    char *c = gs_calc_complement(seq);
    char *rc = gs_calc_reverse(c);
    free(c);
    return rc;
}

void gs_print_reverse_value(const char *seq) {
    printf("Reverse:\n%s\n", seq);
}

void gs_print_complement_value(const char *seq) {
    printf("Complement:\n%s\n", seq);
}

void gs_print_reverse_complement_value(const char *seq) {
    printf("Reverse Complement:\n%s\n", seq);
}

void gs_print_find_motif(const char *seq, const char *motif) {
    printf("Motif:\n");
    size_t mlen = strlen(motif);
    if (mlen == 0) { printf("(empty motif)\n"); return; }
    int found = 0;
    const char *p = seq;
    long base = 1; /* 1-indexed positions */
    while ((p = strstr(p, motif)) != NULL) {
        long pos = base + (long)(p - seq);
        printf("%s -> position %ld\n", motif, pos);
        p += 1;
        found = 1;
    }
    if (!found) printf("%s -> not found\n", motif);
}

static char codon_to_aa(const char *codon) {
    static const struct { const char *codon; char aa; } full[] = {
        {"TTT",'F'},{"TTC",'F'},{"TTA",'L'},{"TTG",'L'},
        {"CTT",'L'},{"CTC",'L'},{"CTA",'L'},{"CTG",'L'},
        {"ATT",'I'},{"ATC",'I'},{"ATA",'I'},{"ATG",'M'},
        {"GTT",'V'},{"GTC",'V'},{"GTA",'V'},{"GTG",'V'},
        {"TCT",'S'},{"TCC",'S'},{"TCA",'S'},{"TCG",'S'},
        {"CCT",'P'},{"CCC",'P'},{"CCA",'P'},{"CCG",'P'},
        {"ACT",'T'},{"ACC",'T'},{"ACA",'T'},{"ACG",'T'},
        {"GCT",'A'},{"GCC",'A'},{"GCA",'A'},{"GCG",'A'},
        {"TAT",'Y'},{"TAC",'Y'},{"TAA",'*'},{"TAG",'*'},
        {"CAT",'H'},{"CAC",'H'},{"CAA",'Q'},{"CAG",'Q'},
        {"AAT",'N'},{"AAC",'N'},{"AAA",'K'},{"AAG",'K'},
        {"GAT",'D'},{"GAC",'D'},{"GAA",'E'},{"GAG",'E'},
        {"TGT",'C'},{"TGC",'C'},{"TGA",'*'},{"TGG",'W'},
        {"CGT",'R'},{"CGC",'R'},{"CGA",'R'},{"CGG",'R'},
        {"AGT",'S'},{"AGC",'S'},{"AGA",'R'},{"AGG",'R'},
        {"GGT",'G'},{"GGC",'G'},{"GGA",'G'},{"GGG",'G'},
    };
    for (size_t i = 0; i < sizeof(full) / sizeof(full[0]); i++) {
        if (strncmp(full[i].codon, codon, 3) == 0) return full[i].aa;
    }
    return 'X';
}

char *gs_calc_translate(const char *seq) {
    size_t len = strlen(seq);
    char *protein = (char *)malloc(len / 3 + 1);
    size_t pi = 0;
    for (size_t i = 0; i + 3 <= len; i += 3) {
        char codon[4] = { (char)toupper((unsigned char)seq[i]),
                           (char)toupper((unsigned char)seq[i + 1]),
                           (char)toupper((unsigned char)seq[i + 2]), '\0' };
        char aa = codon_to_aa(codon);
        if (aa == '*') break;
        protein[pi++] = aa;
    }
    protein[pi] = '\0';
    return protein;
}

void gs_print_protein_value(const char *protein) {
    printf("Protein: %s\n", protein);
}

void gs_print_compare(const char *ref, const char *sample) {
    size_t rlen = strlen(ref), slen = strlen(sample);
    size_t n = rlen < slen ? rlen : slen;

    printf("Mutation Report\n\n");
    if (rlen != slen) {
        printf("Length mismatch: reference=%zu, sample=%zu (comparing over the shorter length)\n",
               rlen, slen);
    }
    int mutations = 0;
    for (size_t i = 0; i < n; i++) {
        if (toupper((unsigned char)ref[i]) != toupper((unsigned char)sample[i])) {
            printf("Position     %zu\n", i + 1);
            printf("Reference    %c\n", ref[i]);
            printf("Sample       %c\n", sample[i]);
            printf("Type         Substitution\n\n");
            mutations++;
        }
    }
    double similarity = rlen > 0 ? (100.0 * (double)(rlen - mutations)) / (double)rlen : 100.0;
    printf("Mutations: %d    Similarity: %.1f%%\n", mutations, similarity);
}

void gs_print_seq_raw(const char *s) {
    printf("%s\n", s);
}
